#pragma once

// <auto-generated>
// Source: tools/native-hooks/papyrus_lootman_hooks.addresses.json
// Target runtime: Fallout4 1.11.240
// Regenerate from repository root: pnpm run native-hooks:generate
// </auto-generated>

#include <array>
#include <cstdint>
#include <span>
#include <REL/ID.h>

namespace papyrus_lootman
{
	struct NativeHookCallSite
	{
		const char* id;
		std::uintptr_t rva;
		std::uint32_t sourceId;
		const char* label;
		std::uintptr_t expectedTargetRva;
		std::span<const std::uint8_t> contextBytes;
	};

	inline constexpr std::uint32_t kNativeHookContextSignatureVersion = 1;

	inline constexpr std::array<std::uint8_t, 3> kLoadChangeCellBeforeZoneResetCallSiteContext0{ 0x88, 0x45, 0x67 };

	inline constexpr NativeHookCallSite kLoadChangeCellBeforeZoneResetCallSite{
		"encounter-zone.reset-suppression.cell-before-reset",
		0x4D26F4,
		0x0,
		"encounter-zone.reset-suppression.cell-before-reset@0x4D26F4",
		0x494E60,
		kLoadChangeCellBeforeZoneResetCallSiteContext0,
	};

	// Address Library offset: 0x4D3150
	inline constexpr REL::ID kEncounterZoneResetElapsedFromDetachId{ 2200355 };

	// Address Library offset: 0x30F7AB8
	inline constexpr REL::ID kWorkshopCaravanKeywordGlobalId{ 4797310 };

	// Address Library offset: 0x30F7698
	inline constexpr REL::ID kCurrentWorkshopHandleGlobalId{ 4797241 };

	inline constexpr std::array<std::uint8_t, 2> kPopulateLinkedWorkshopContainerCallSitesContext0{ 0xEB, 0x27 };
	inline constexpr std::array<std::uint8_t, 4> kPopulateLinkedWorkshopContainerCallSitesContext1{ 0x44, 0x8B, 0x4F, 0x10 };
	inline constexpr std::array<std::uint8_t, 4> kPopulateLinkedWorkshopContainerCallSitesContext2{ 0x48, 0x8B, 0x45, 0x7F };

	inline constexpr std::array<NativeHookCallSite, 3> kPopulateLinkedWorkshopContainerCallSites{{
		{
			"workshop-shared-container.populate-linked.primary",
			0x3922A8,
			0x0,
			"workshop-shared-container.populate-linked.primary@0x3922A8",
			0x38A140,
			kPopulateLinkedWorkshopContainerCallSitesContext0,
		},
		{
			"workshop-shared-container.populate-linked.workbench",
			0xB28966,
			0x0,
			"workshop-shared-container.populate-linked.workbench@0xB28966",
			0x38A140,
			kPopulateLinkedWorkshopContainerCallSitesContext1,
		},
		{
			"workshop-shared-container.populate-linked.menu",
			0x10895E6,
			0x0,
			"workshop-shared-container.populate-linked.menu@0x10895E6",
			0x38A140,
			kPopulateLinkedWorkshopContainerCallSitesContext2,
		},
	}};

	inline constexpr std::array<std::uint8_t, 6> kRebuildWorkshopSupplyCallSitesContext0{ 0x48, 0x83, 0x7C, 0x24, 0x28, 0x00 };
	inline constexpr std::array<std::uint8_t, 3> kRebuildWorkshopSupplyCallSitesContext1{ 0x48, 0x8B, 0x07 };
	inline constexpr std::array<std::uint8_t, 5> kRebuildWorkshopSupplyCallSitesContext2{ 0x48, 0x83, 0x7D, 0xA0, 0x00 };
	inline constexpr std::array<std::uint8_t, 3> kRebuildWorkshopSupplyCallSitesContext3{ 0x48, 0x8B, 0x1F };

	inline constexpr std::array<NativeHookCallSite, 4> kRebuildWorkshopSupplyCallSites{{
		{
			"workshop-material.rebuild-supply.source-a1",
			0xA65746,
			0xA1,
			"workshop-material.rebuild-supply.source-a1@0xA65746",
			0xB29480,
			kRebuildWorkshopSupplyCallSitesContext0,
		},
		{
			"workshop-material.rebuild-supply.source-a2",
			0xA5F459,
			0xA2,
			"workshop-material.rebuild-supply.source-a2@0xA5F459",
			0xB29480,
			kRebuildWorkshopSupplyCallSitesContext1,
		},
		{
			"workshop-material.rebuild-supply.source-a3",
			0xA6087C,
			0xA3,
			"workshop-material.rebuild-supply.source-a3@0xA6087C",
			0xB29480,
			kRebuildWorkshopSupplyCallSitesContext2,
		},
		{
			"workshop-material.rebuild-supply.source-a4",
			0xAEF9A9,
			0xA4,
			"workshop-material.rebuild-supply.source-a4@0xAEF9A9",
			0xB29480,
			kRebuildWorkshopSupplyCallSitesContext3,
		},
	}};

	inline constexpr std::array<std::uint8_t, 4> kComponentCountHelperCallSitesContext0{ 0x8B, 0x44, 0x24, 0x30 };
	inline constexpr std::array<std::uint8_t, 2> kComponentCountHelperCallSitesContext1{ 0x84, 0xC0 };

	inline constexpr std::array<NativeHookCallSite, 2> kComponentCountHelperCallSites{{
		{
			"workshop-material.component-count.papyrus",
			0x59BF5A,
			0xB1,
			"workshop-material.component-count.papyrus@0x59BF5A",
			0x507990,
			kComponentCountHelperCallSitesContext0,
		},
		{
			"workshop-material.component-count.workbench-ui",
			0x117550B,
			0xB2,
			"workshop-material.component-count.workbench-ui@0x117550B",
			0x507990,
			kComponentCountHelperCallSitesContext1,
		},
	}};

	inline constexpr std::array<std::uint8_t, 2> kDirectComponentCountCallSitesContext0{ 0x03, 0xF0 };
	inline constexpr std::array<std::uint8_t, 5> kDirectComponentCountCallSitesContext1{ 0x03, 0xE8, 0x49, 0x8B, 0xCE };
	inline constexpr std::array<std::uint8_t, 9> kDirectComponentCountCallSitesContext2{ 0x03, 0xE8, 0x48, 0x8B, 0x0D, 0xBF, 0x0C, 0x74, 0x02 };
	inline constexpr std::array<std::uint8_t, 2> kDirectComponentCountCallSitesContext3{ 0x03, 0xF8 };
	inline constexpr std::array<std::uint8_t, 6> kDirectComponentCountCallSitesContext4{ 0x01, 0x85, 0xF0, 0x00, 0x00, 0x00 };

	inline constexpr std::array<NativeHookCallSite, 5> kDirectComponentCountCallSites{{
		{
			"workshop-material.direct-component-count.source-e1",
			0x3BC71D,
			0xE1,
			"workshop-material.direct-component-count.source-e1@0x3BC71D",
			0x507D30,
			kDirectComponentCountCallSitesContext0,
		},
		{
			"workshop-material.direct-component-count.source-e2",
			0x39F5AF,
			0xE2,
			"workshop-material.direct-component-count.source-e2@0x39F5AF",
			0x507D30,
			kDirectComponentCountCallSitesContext1,
		},
		{
			"workshop-material.direct-component-count.source-e3",
			0xB32E7B,
			0xE3,
			"workshop-material.direct-component-count.source-e3@0xB32E7B",
			0x507D30,
			kDirectComponentCountCallSitesContext2,
		},
		{
			"workshop-material.direct-component-count.source-e4",
			0xB37828,
			0xE4,
			"workshop-material.direct-component-count.source-e4@0xB37828",
			0x507D30,
			kDirectComponentCountCallSitesContext3,
		},
		{
			"workshop-material.direct-component-count.source-e5",
			0xB2D13E,
			0xE5,
			"workshop-material.direct-component-count.source-e5@0xB2D13E",
			0x507D30,
			kDirectComponentCountCallSitesContext4,
		},
	}};

	inline constexpr std::array<std::uint8_t, 4> kWorkshopResourceStatusCallSitesContext0{ 0x48, 0x8B, 0x4B, 0x20 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopResourceStatusCallSitesContext1{ 0x48, 0x8D, 0x4D, 0xF8 };

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopResourceStatusCallSites{{
		{
			"workshop-material.resource-status.source-f1",
			0xB2F0B0,
			0xF1,
			"workshop-material.resource-status.source-f1@0xB2F0B0",
			0xB32DA0,
			kWorkshopResourceStatusCallSitesContext0,
		},
		{
			"workshop-material.resource-status.source-f2",
			0xB2D056,
			0xF2,
			"workshop-material.resource-status.source-f2@0xB2D056",
			0xB32DA0,
			kWorkshopResourceStatusCallSitesContext1,
		},
	}};

	inline constexpr std::array<std::uint8_t, 7> kWorkshopMenuSelectCallSitesContext0{ 0x0F, 0xB7, 0x0D, 0x72, 0xA8, 0x5C, 0x02 };
	inline constexpr std::array<std::uint8_t, 7> kWorkshopMenuSelectCallSitesContext1{ 0x0F, 0xB7, 0x0D, 0xB5, 0xA5, 0x5C, 0x02 };

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopMenuSelectCallSites{{
		{
			"workshop-menu.select.source-a1",
			0xB2C69A,
			0xA1,
			"workshop-menu.select.source-a1@0xB2C69A",
			0x3970E0,
			kWorkshopMenuSelectCallSitesContext0,
		},
		{
			"workshop-menu.select.source-a2",
			0xB2C957,
			0xA2,
			"workshop-menu.select.source-a2@0xB2C957",
			0x3970E0,
			kWorkshopMenuSelectCallSitesContext1,
		},
	}};

	inline constexpr std::array<std::uint8_t, 6> kWorkshopMenuAvailabilityCallSitesContext0{ 0x8B, 0x8D, 0xF8, 0x00, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext1{ 0x8B, 0x4D, 0xA0 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext2{ 0x8B, 0x4D, 0xA4 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext3{ 0x8B, 0x4D, 0xA8 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext4{ 0x8B, 0x4C, 0x24, 0x70 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext5{ 0x84, 0xC0, 0x74, 0x0C };
	inline constexpr std::array<std::uint8_t, 12> kWorkshopMenuAvailabilityCallSitesContext6{ 0x84, 0xC0, 0x74, 0x3C, 0x83, 0xBC, 0x24, 0xA0, 0x00, 0x00, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 12> kWorkshopMenuAvailabilityCallSitesContext7{ 0x84, 0xC0, 0x74, 0x3C, 0x83, 0xBC, 0x24, 0x98, 0x00, 0x00, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext8{ 0x8B, 0x4C, 0x24, 0x24 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext9{ 0x8B, 0x4D, 0xC4 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext10{ 0x8B, 0x4D, 0xC8 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext11{ 0x8B, 0x4C, 0x24, 0x4C };
	inline constexpr std::array<std::uint8_t, 9> kWorkshopMenuAvailabilityCallSitesContext12{ 0x84, 0xC0, 0x74, 0x11, 0x83, 0x7C, 0x24, 0x48, 0x00 };
	inline constexpr std::array<std::uint8_t, 11> kWorkshopMenuAvailabilityCallSitesContext13{ 0x84, 0xC0, 0x74, 0x11, 0x44, 0x39, 0xB5, 0xB0, 0x01, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext14{ 0x8B, 0x4C, 0x24, 0x38 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopMenuAvailabilityCallSitesContext15{ 0x8B, 0x4D, 0x87 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopMenuAvailabilityCallSitesContext16{ 0x44, 0x8B, 0x45, 0xAF };
	inline constexpr std::array<std::uint8_t, 7> kWorkshopMenuAvailabilityCallSitesContext17{ 0x8B, 0x8C, 0x24, 0x88, 0x00, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 5> kWorkshopMenuAvailabilityCallSitesContext18{ 0x44, 0x8B, 0x4C, 0x24, 0x70 };

	inline constexpr std::array<NativeHookCallSite, 19> kWorkshopMenuAvailabilityCallSites{{
		{
			"workshop-menu.availability.source-91",
			0xB2C65E,
			0x91,
			"workshop-menu.availability.source-91@0xB2C65E",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext0,
		},
		{
			"workshop-menu.availability.source-92",
			0xB2C6C7,
			0x92,
			"workshop-menu.availability.source-92@0xB2C6C7",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext1,
		},
		{
			"workshop-menu.availability.source-93",
			0xB2C91E,
			0x93,
			"workshop-menu.availability.source-93@0xB2C91E",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext2,
		},
		{
			"workshop-menu.availability.source-94",
			0xB2C984,
			0x94,
			"workshop-menu.availability.source-94@0xB2C984",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext3,
		},
		{
			"workshop-menu.availability.source-95",
			0xB2E9D4,
			0x95,
			"workshop-menu.availability.source-95@0xB2E9D4",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext4,
		},
		{
			"workshop-menu.availability.source-96",
			0x397185,
			0x96,
			"workshop-menu.availability.source-96@0x397185",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext5,
		},
		{
			"workshop-menu.availability.source-97",
			0x3B82D2,
			0x97,
			"workshop-menu.availability.source-97@0x3B82D2",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext6,
		},
		{
			"workshop-menu.availability.source-98",
			0x3C1BCF,
			0x98,
			"workshop-menu.availability.source-98@0x3C1BCF",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext7,
		},
		{
			"workshop-menu.availability.source-99",
			0xB2B894,
			0x99,
			"workshop-menu.availability.source-99@0xB2B894",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext8,
		},
		{
			"workshop-menu.availability.source-9a",
			0xB2D75F,
			0x9A,
			"workshop-menu.availability.source-9a@0xB2D75F",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext9,
		},
		{
			"workshop-menu.availability.source-9b",
			0xB2D891,
			0x9B,
			"workshop-menu.availability.source-9b@0xB2D891",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext10,
		},
		{
			"workshop-menu.availability.source-9c",
			0xB2ECFF,
			0x9C,
			"workshop-menu.availability.source-9c@0xB2ECFF",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext11,
		},
		{
			"workshop-menu.availability.source-9d",
			0xB3035B,
			0x9D,
			"workshop-menu.availability.source-9d@0xB3035B",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext12,
		},
		{
			"workshop-menu.availability.source-9e",
			0xB323A5,
			0x9E,
			"workshop-menu.availability.source-9e@0xB323A5",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext13,
		},
		{
			"workshop-menu.availability.source-9f",
			0xB330EC,
			0x9F,
			"workshop-menu.availability.source-9f@0xB330EC",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext14,
		},
		{
			"workshop-menu.availability.source-a0",
			0xB36148,
			0xA0,
			"workshop-menu.availability.source-a0@0xB36148",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext15,
		},
		{
			"workshop-menu.availability.source-a1",
			0xB36651,
			0xA1,
			"workshop-menu.availability.source-a1@0xB36651",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext16,
		},
		{
			"workshop-menu.availability.source-a2",
			0xB37630,
			0xA2,
			"workshop-menu.availability.source-a2@0xB37630",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext17,
		},
		{
			"workshop-menu.availability.source-a3",
			0xB376DB,
			0xA3,
			"workshop-menu.availability.source-a3@0xB376DB",
			0x399AD0,
			kWorkshopMenuAvailabilityCallSitesContext18,
		},
	}};

	inline constexpr std::array<std::uint8_t, 5> kWorkshopCheckAndSetPlacementCallSitesContext0{ 0xE8, 0xFF, 0x33, 0xEB, 0xFF };
	inline constexpr std::array<std::uint8_t, 9> kWorkshopCheckAndSetPlacementCallSitesContext1{ 0x40, 0x84, 0xF6, 0x0F, 0x84, 0xC5, 0x03, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 9> kWorkshopCheckAndSetPlacementCallSitesContext2{ 0x40, 0x84, 0xF6, 0x0F, 0x84, 0x08, 0x01, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopCheckAndSetPlacementCallSitesContext3{ 0x44, 0x39, 0x65, 0x20 };

	inline constexpr std::array<NativeHookCallSite, 4> kWorkshopCheckAndSetPlacementCallSites{{
		{
			"workshop-menu.check-placement.source-a5",
			0xB2B0F7,
			0xA5,
			"workshop-menu.check-placement.source-a5@0xB2B0F7",
			0xB2E940,
			kWorkshopCheckAndSetPlacementCallSitesContext0,
		},
		{
			"workshop-menu.check-placement.source-a6",
			0xB2C6E2,
			0xA6,
			"workshop-menu.check-placement.source-a6@0xB2C6E2",
			0xB2E940,
			kWorkshopCheckAndSetPlacementCallSitesContext1,
		},
		{
			"workshop-menu.check-placement.source-a7",
			0xB2C99F,
			0xA7,
			"workshop-menu.check-placement.source-a7@0xB2C99F",
			0xB2E940,
			kWorkshopCheckAndSetPlacementCallSitesContext2,
		},
		{
			"workshop-menu.check-placement.source-a8",
			0xB2E67E,
			0xA8,
			"workshop-menu.check-placement.source-a8@0xB2E67E",
			0xB2E940,
			kWorkshopCheckAndSetPlacementCallSitesContext3,
		},
	}};

	inline constexpr std::array<std::uint8_t, 3> kWorkshopStartPlacementCallSitesContext0{ 0x8B, 0x45, 0x30 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopStartPlacementCallSitesContext1{ 0x8B, 0x45, 0x50 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopStartPlacementCallSitesContext2{ 0x48, 0x8B, 0xCE };
	inline constexpr std::array<std::uint8_t, 10> kWorkshopStartPlacementCallSitesContext3{ 0x33, 0xD2, 0x48, 0x8B, 0xCE, 0xE8, 0x7D, 0x50, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 5> kWorkshopStartPlacementCallSitesContext4{ 0xE9, 0xB3, 0x00, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 3> kWorkshopStartPlacementCallSitesContext5{ 0x48, 0x8B, 0xCF };
	inline constexpr std::array<std::uint8_t, 10> kWorkshopStartPlacementCallSitesContext6{ 0x33, 0xD2, 0x48, 0x8B, 0xCE, 0xE8, 0xD2, 0x20, 0x00, 0x00 };

	inline constexpr std::array<NativeHookCallSite, 7> kWorkshopStartPlacementCallSites{{
		{
			"workshop-menu.start-placement.source-a3",
			0xB2C7DA,
			0xA3,
			"workshop-menu.start-placement.source-a3@0xB2C7DA",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext0,
		},
		{
			"workshop-menu.start-placement.source-a4",
			0xB2CA95,
			0xA4,
			"workshop-menu.start-placement.source-a4@0xB2CA95",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext1,
		},
		{
			"workshop-menu.start-placement.source-a9",
			0xB2B0EF,
			0xA9,
			"workshop-menu.start-placement.source-a9@0xB2B0EF",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext2,
		},
		{
			"workshop-menu.start-placement.source-aa",
			0xB2B954,
			0xAA,
			"workshop-menu.start-placement.source-aa@0xB2B954",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext3,
		},
		{
			"workshop-menu.start-placement.source-ab",
			0xB2D900,
			0xAB,
			"workshop-menu.start-placement.source-ab@0xB2D900",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext4,
		},
		{
			"workshop-menu.start-placement.source-ac",
			0xB2E676,
			0xAC,
			"workshop-menu.start-placement.source-ac@0xB2E676",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext5,
		},
		{
			"workshop-menu.start-placement.source-ad",
			0xB2E8FF,
			0xAD,
			"workshop-menu.start-placement.source-ad@0xB2E8FF",
			0xB2FF30,
			kWorkshopStartPlacementCallSitesContext6,
		},
	}};

	inline constexpr std::array<std::uint8_t, 8> kWorkshopBuildResourceCheckCallSitesContext0{ 0x84, 0xC0, 0x0F, 0x84, 0x50, 0x04, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 8> kWorkshopBuildResourceCheckCallSitesContext1{ 0x84, 0xC0, 0x0F, 0x84, 0x2A, 0x08, 0x00, 0x00 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopBuildResourceCheckCallSitesContext2{ 0x48, 0x8B, 0x4B, 0x18 };

	inline constexpr std::array<NativeHookCallSite, 3> kWorkshopBuildResourceCheckCallSites{{
		{
			"workshop-material.build-resource-check.placement",
			0x392844,
			0xB1,
			"workshop-material.build-resource-check.placement@0x392844",
			0x42BFF0,
			kWorkshopBuildResourceCheckCallSitesContext0,
		},
		{
			"workshop-material.build-resource-check.confirm",
			0x399136,
			0xB2,
			"workshop-material.build-resource-check.confirm@0x399136",
			0x42BFF0,
			kWorkshopBuildResourceCheckCallSitesContext1,
		},
		{
			"workshop-material.build-resource-check.consume-precheck",
			0x3B7F7E,
			0xB3,
			"workshop-material.build-resource-check.consume-precheck@0x3B7F7E",
			0x42BFF0,
			kWorkshopBuildResourceCheckCallSitesContext2,
		},
	}};

	inline constexpr std::array<std::uint8_t, 4> kWorkshopConsumeComponentCallSitesContext0{ 0x48, 0x83, 0xC7, 0x10 };
	inline constexpr std::array<std::uint8_t, 4> kWorkshopConsumeComponentCallSitesContext1{ 0x48, 0x83, 0xC3, 0x10 };

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopConsumeComponentCallSites{{
		{
			"workshop-material.consume-component.source-f3",
			0x399326,
			0xF3,
			"workshop-material.consume-component.source-f3@0x399326",
			0x392340,
			kWorkshopConsumeComponentCallSitesContext0,
		},
		{
			"workshop-material.consume-component.source-f4",
			0x3B805A,
			0xF4,
			"workshop-material.consume-component.source-f4@0x3B805A",
			0x392340,
			kWorkshopConsumeComponentCallSitesContext1,
		},
	}};

	// Address Library: RE::ID::Workshop::GetSelectedWorkshopMenuNode @ 0x389DB0
	inline constexpr REL::ID kWorkshopSelectedMenuNodeFunctionId{ 2195024 };

	// Address Library: RE::ID::Workshop::CurrentRow @ 0x30F6F18
	inline constexpr REL::ID kWorkshopSelectedRowGlobalId{ 4797160 };

	inline constexpr std::uint32_t kWorkshopResourceStatusMissingResources = 0x2;

	inline constexpr std::array<std::uint8_t, 4> kRemoveComponentsCallSitesContext0{ 0x48, 0x83, 0xC3, 0x10 };
	inline constexpr std::array<std::uint8_t, 5> kRemoveComponentsCallSitesContext1{ 0xE9, 0xB7, 0x00, 0x00, 0x00 };

	inline constexpr std::array<NativeHookCallSite, 2> kRemoveComponentsCallSites{{
		{
			"workshop-material.remove-components.source-f1",
			0x114F009,
			0xF1,
			"workshop-material.remove-components.source-f1@0x114F009",
			0x1182A90,
			kRemoveComponentsCallSitesContext0,
		},
		{
			"workshop-material.remove-components.source-f2",
			0x114EA33,
			0xF2,
			"workshop-material.remove-components.source-f2@0x114EA33",
			0x1182A90,
			kRemoveComponentsCallSitesContext1,
		},
	}};

	inline constexpr std::array<std::uint8_t, 7> kWorkshopObjectCountPapyrusCallSiteContext0{ 0x48, 0x81, 0xC4, 0xC0, 0x00, 0x00, 0x00 };

	inline constexpr NativeHookCallSite kWorkshopObjectCountPapyrusCallSite{
		"workshop-material.object-count.papyrus",
		0x5DD7B4,
		0xC1,
		"workshop-material.object-count.papyrus@0x5DD7B4",
		0x59D690,
		kWorkshopObjectCountPapyrusCallSiteContext0,
	};

	inline constexpr std::array<std::uint8_t, 2> kCurrentWorkshopObjectCountCallSiteContext0{ 0x8B, 0xC0 };

	inline constexpr NativeHookCallSite kCurrentWorkshopObjectCountCallSite{
		"workshop-material.object-count.current-workshop",
		0x59D6A8,
		0xC2,
		"workshop-material.object-count.current-workshop@0x59D6A8",
		0x37E190,
		kCurrentWorkshopObjectCountCallSiteContext0,
	};

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldE0Offset = 0xE0;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldE8Offset = 0xE8;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldF8Offset = 0xF8;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerField2F8Offset = 0x2F8;

}
