#pragma once

// <auto-generated>
// Source: tools/native-hooks/papyrus_lootman_hooks.addresses.json
// Target runtime: Fallout4 1.11.191
// Regenerate from packaging/: pnpm run generate:native-hooks
// </auto-generated>

#include <array>
#include <cstdint>
#include <REL/ID.h>

namespace papyrus_lootman
{
	struct NativeHookCallSite
	{
		const char* id;
		std::uintptr_t rva;
		std::uint32_t sourceId;
		const char* label;
	};

	inline constexpr NativeHookCallSite kLoadChangeCellBeforeZoneResetCallSite{
		"encounter-zone.reset-suppression.cell-before-reset",
		0x4D23C4,
		0x0,
		"encounter-zone.reset-suppression.cell-before-reset@0x4D23C4",
	};

	// Address Library offset: 0x4D2E20
	inline constexpr REL::ID kEncounterZoneResetElapsedFromDetachId{ 2200355 };

	// Address Library offset: 0x30EC9B8
	inline constexpr REL::ID kWorkshopCaravanKeywordGlobalId{ 4797310 };

	// Address Library offset: 0x30EC598
	inline constexpr REL::ID kCurrentWorkshopHandleGlobalId{ 4797241 };

	inline constexpr std::array<NativeHookCallSite, 3> kPopulateLinkedWorkshopContainerCallSites{{
		{
			"workshop-shared-container.populate-linked.primary",
			0x391F78,
			0x0,
			"workshop-shared-container.populate-linked.primary@0x391F78",
		},
		{
			"workshop-shared-container.populate-linked.workbench",
			0xB28B76,
			0x0,
			"workshop-shared-container.populate-linked.workbench@0xB28B76",
		},
		{
			"workshop-shared-container.populate-linked.menu",
			0x10890F6,
			0x0,
			"workshop-shared-container.populate-linked.menu@0x10890F6",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 4> kRebuildWorkshopSupplyCallSites{{
		{
			"workshop-material.rebuild-supply.source-a1",
			0xA653F6,
			0xA1,
			"workshop-material.rebuild-supply.source-a1@0xA653F6",
		},
		{
			"workshop-material.rebuild-supply.source-a2",
			0xA5F109,
			0xA2,
			"workshop-material.rebuild-supply.source-a2@0xA5F109",
		},
		{
			"workshop-material.rebuild-supply.source-a3",
			0xA6052C,
			0xA3,
			"workshop-material.rebuild-supply.source-a3@0xA6052C",
		},
		{
			"workshop-material.rebuild-supply.source-a4",
			0xAEFD89,
			0xA4,
			"workshop-material.rebuild-supply.source-a4@0xAEFD89",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 2> kComponentCountHelperCallSites{{
		{
			"workshop-material.component-count.papyrus",
			0x59BC2A,
			0xB1,
			"workshop-material.component-count.papyrus@0x59BC2A",
		},
		{
			"workshop-material.component-count.workbench-ui",
			0x117501B,
			0xB2,
			"workshop-material.component-count.workbench-ui@0x117501B",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 5> kDirectComponentCountCallSites{{
		{
			"workshop-material.direct-component-count.source-e1",
			0x3BC3ED,
			0xE1,
			"workshop-material.direct-component-count.source-e1@0x3BC3ED",
		},
		{
			"workshop-material.direct-component-count.source-e2",
			0x39F27F,
			0xE2,
			"workshop-material.direct-component-count.source-e2@0x39F27F",
		},
		{
			"workshop-material.direct-component-count.source-e3",
			0xB3308B,
			0xE3,
			"workshop-material.direct-component-count.source-e3@0xB3308B",
		},
		{
			"workshop-material.direct-component-count.source-e4",
			0xB37A38,
			0xE4,
			"workshop-material.direct-component-count.source-e4@0xB37A38",
		},
		{
			"workshop-material.direct-component-count.source-e5",
			0xB2D34E,
			0xE5,
			"workshop-material.direct-component-count.source-e5@0xB2D34E",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopResourceStatusCallSites{{
		{
			"workshop-material.resource-status.source-f1",
			0xB2F2C0,
			0xF1,
			"workshop-material.resource-status.source-f1@0xB2F2C0",
		},
		{
			"workshop-material.resource-status.source-f2",
			0xB2D266,
			0xF2,
			"workshop-material.resource-status.source-f2@0xB2D266",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopMenuSelectCallSites{{
		{
			"workshop-menu.select.source-a1",
			0xB2C8AA,
			0xA1,
			"workshop-menu.select.source-a1@0xB2C8AA",
		},
		{
			"workshop-menu.select.source-a2",
			0xB2CB67,
			0xA2,
			"workshop-menu.select.source-a2@0xB2CB67",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 19> kWorkshopMenuAvailabilityCallSites{{
		{
			"workshop-menu.availability.source-91",
			0xB2C86E,
			0x91,
			"workshop-menu.availability.source-91@0xB2C86E",
		},
		{
			"workshop-menu.availability.source-92",
			0xB2C8D7,
			0x92,
			"workshop-menu.availability.source-92@0xB2C8D7",
		},
		{
			"workshop-menu.availability.source-93",
			0xB2CB2E,
			0x93,
			"workshop-menu.availability.source-93@0xB2CB2E",
		},
		{
			"workshop-menu.availability.source-94",
			0xB2CB94,
			0x94,
			"workshop-menu.availability.source-94@0xB2CB94",
		},
		{
			"workshop-menu.availability.source-95",
			0xB2EBE4,
			0x95,
			"workshop-menu.availability.source-95@0xB2EBE4",
		},
		{
			"workshop-menu.availability.source-96",
			0x396E55,
			0x96,
			"workshop-menu.availability.source-96@0x396E55",
		},
		{
			"workshop-menu.availability.source-97",
			0x3B7FA2,
			0x97,
			"workshop-menu.availability.source-97@0x3B7FA2",
		},
		{
			"workshop-menu.availability.source-98",
			0x3C189F,
			0x98,
			"workshop-menu.availability.source-98@0x3C189F",
		},
		{
			"workshop-menu.availability.source-99",
			0xB2BAA4,
			0x99,
			"workshop-menu.availability.source-99@0xB2BAA4",
		},
		{
			"workshop-menu.availability.source-9a",
			0xB2D96F,
			0x9A,
			"workshop-menu.availability.source-9a@0xB2D96F",
		},
		{
			"workshop-menu.availability.source-9b",
			0xB2DAA1,
			0x9B,
			"workshop-menu.availability.source-9b@0xB2DAA1",
		},
		{
			"workshop-menu.availability.source-9c",
			0xB2EF0F,
			0x9C,
			"workshop-menu.availability.source-9c@0xB2EF0F",
		},
		{
			"workshop-menu.availability.source-9d",
			0xB3056B,
			0x9D,
			"workshop-menu.availability.source-9d@0xB3056B",
		},
		{
			"workshop-menu.availability.source-9e",
			0xB325B5,
			0x9E,
			"workshop-menu.availability.source-9e@0xB325B5",
		},
		{
			"workshop-menu.availability.source-9f",
			0xB332FC,
			0x9F,
			"workshop-menu.availability.source-9f@0xB332FC",
		},
		{
			"workshop-menu.availability.source-a0",
			0xB36358,
			0xA0,
			"workshop-menu.availability.source-a0@0xB36358",
		},
		{
			"workshop-menu.availability.source-a1",
			0xB36861,
			0xA1,
			"workshop-menu.availability.source-a1@0xB36861",
		},
		{
			"workshop-menu.availability.source-a2",
			0xB37840,
			0xA2,
			"workshop-menu.availability.source-a2@0xB37840",
		},
		{
			"workshop-menu.availability.source-a3",
			0xB378EB,
			0xA3,
			"workshop-menu.availability.source-a3@0xB378EB",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 4> kWorkshopCheckAndSetPlacementCallSites{{
		{
			"workshop-menu.check-placement.source-a5",
			0xB2B307,
			0xA5,
			"workshop-menu.check-placement.source-a5@0xB2B307",
		},
		{
			"workshop-menu.check-placement.source-a6",
			0xB2C8F2,
			0xA6,
			"workshop-menu.check-placement.source-a6@0xB2C8F2",
		},
		{
			"workshop-menu.check-placement.source-a7",
			0xB2CBAF,
			0xA7,
			"workshop-menu.check-placement.source-a7@0xB2CBAF",
		},
		{
			"workshop-menu.check-placement.source-a8",
			0xB2E88E,
			0xA8,
			"workshop-menu.check-placement.source-a8@0xB2E88E",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 7> kWorkshopStartPlacementCallSites{{
		{
			"workshop-menu.start-placement.source-a3",
			0xB2C9EA,
			0xA3,
			"workshop-menu.start-placement.source-a3@0xB2C9EA",
		},
		{
			"workshop-menu.start-placement.source-a4",
			0xB2CCA5,
			0xA4,
			"workshop-menu.start-placement.source-a4@0xB2CCA5",
		},
		{
			"workshop-menu.start-placement.source-a9",
			0xB2B2FF,
			0xA9,
			"workshop-menu.start-placement.source-a9@0xB2B2FF",
		},
		{
			"workshop-menu.start-placement.source-aa",
			0xB2BB64,
			0xAA,
			"workshop-menu.start-placement.source-aa@0xB2BB64",
		},
		{
			"workshop-menu.start-placement.source-ab",
			0xB2DB10,
			0xAB,
			"workshop-menu.start-placement.source-ab@0xB2DB10",
		},
		{
			"workshop-menu.start-placement.source-ac",
			0xB2E886,
			0xAC,
			"workshop-menu.start-placement.source-ac@0xB2E886",
		},
		{
			"workshop-menu.start-placement.source-ad",
			0xB2EB0F,
			0xAD,
			"workshop-menu.start-placement.source-ad@0xB2EB0F",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 3> kWorkshopBuildResourceCheckCallSites{{
		{
			"workshop-material.build-resource-check.placement",
			0x392514,
			0xB1,
			"workshop-material.build-resource-check.placement@0x392514",
		},
		{
			"workshop-material.build-resource-check.confirm",
			0x398E06,
			0xB2,
			"workshop-material.build-resource-check.confirm@0x398E06",
		},
		{
			"workshop-material.build-resource-check.consume-precheck",
			0x3B7C4E,
			0xB3,
			"workshop-material.build-resource-check.consume-precheck@0x3B7C4E",
		},
	}};

	inline constexpr std::array<NativeHookCallSite, 2> kWorkshopConsumeComponentCallSites{{
		{
			"workshop-material.consume-component.source-f3",
			0x398FF6,
			0xF3,
			"workshop-material.consume-component.source-f3@0x398FF6",
		},
		{
			"workshop-material.consume-component.source-f4",
			0x3B7D2A,
			0xF4,
			"workshop-material.consume-component.source-f4@0x3B7D2A",
		},
	}};

	// Address Library: RE::ID::Workshop::GetSelectedWorkshopMenuNode @ 0x389A80
	inline constexpr REL::ID kWorkshopSelectedMenuNodeFunctionId{ 2195024 };

	// Address Library: RE::ID::Workshop::CurrentRow @ 0x30EBE18
	inline constexpr REL::ID kWorkshopSelectedRowGlobalId{ 4797160 };

	inline constexpr std::uint32_t kWorkshopResourceStatusMissingResources = 0x2;

	inline constexpr std::array<NativeHookCallSite, 2> kRemoveComponentsCallSites{{
		{
			"workshop-material.remove-components.source-f1",
			0x114EB19,
			0xF1,
			"workshop-material.remove-components.source-f1@0x114EB19",
		},
		{
			"workshop-material.remove-components.source-f2",
			0x114E543,
			0xF2,
			"workshop-material.remove-components.source-f2@0x114E543",
		},
	}};

	inline constexpr NativeHookCallSite kWorkshopObjectCountPapyrusCallSite{
		"workshop-material.object-count.papyrus",
		0x5DD484,
		0xC1,
		"workshop-material.object-count.papyrus@0x5DD484",
	};

	inline constexpr NativeHookCallSite kCurrentWorkshopObjectCountCallSite{
		"workshop-material.object-count.current-workshop",
		0x59D378,
		0xC2,
		"workshop-material.object-count.current-workshop@0x59D378",
	};

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldE0Offset = 0xE0;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldE8Offset = 0xE8;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerFieldF8Offset = 0xF8;

	inline constexpr std::uintptr_t kWorkshopSupplyOwnerField2F8Offset = 0x2F8;

}
